### ISSUE TITLE
Branching threshold

### ISSUE THREAD

**Issue by n-gao** [bytedance/jaqmc#4]
In `branch_fix_size.py` the threshold to decide which walker to remove is calculated as 
```python
thresholds = smallest_k_indices[:, 0] / (smallest_k_indices[:, 0] + smallest_k_indices[:, 1])
```
Why is it based on the ratio between the indices? Shouldn't this be:
```python
thresholds = weight[smallest_k_indices[:, 0]] / (weight[smallest_k_indices[:, 0]] + weight[smallest_k_indices[:, 1]])
```

**Comment by WeiluoRen-ByteDance** [comment]
Hey Nicholas @n-gao , Thanks for raising this issue. I think you are right, it's a bug and we should go with your proposal. Luckily it probably doesn't affect much, since it's only used to determine which walker to choose when merging two small ones. 

Thanks again! I will make sure it's first thing on my list tomorrow.
